/* Generated by wayland-scanner 1.23.1 */

#ifndef KYWC_OUTPUT_V1_CLIENT_PROTOCOL_H
#define KYWC_OUTPUT_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_kywc_output_v1 The kywc_output_v1 protocol
 * @section page_ifaces_kywc_output_v1 Interfaces
 * - @subpage page_iface_kywc_output_manager_v1 - output device configuration manager
 * - @subpage page_iface_kywc_output_v1 - output device
 * - @subpage page_iface_kywc_output_mode_v1 - output mode
 * @section page_copyright_kywc_output_v1 Copyright
 * <pre>
 *
 * SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
 * SPDX-License-Identifier: MulanPSL-2.0
 * </pre>
 */
struct kywc_output_manager_v1;
struct kywc_output_mode_v1;
struct kywc_output_v1;

#ifndef KYWC_OUTPUT_MANAGER_V1_INTERFACE
#define KYWC_OUTPUT_MANAGER_V1_INTERFACE
/**
 * @page page_iface_kywc_output_manager_v1 kywc_output_manager_v1
 * @section page_iface_kywc_output_manager_v1_desc Description
 *
 * This interface is a manager that allows reading and writing the current
 * output device configuration.
 * @section page_iface_kywc_output_manager_v1_api API
 * See @ref iface_kywc_output_manager_v1.
 */
/**
 * @defgroup iface_kywc_output_manager_v1 The kywc_output_manager_v1 interface
 *
 * This interface is a manager that allows reading and writing the current
 * output device configuration.
 */
extern const struct wl_interface kywc_output_manager_v1_interface;
#endif
#ifndef KYWC_OUTPUT_V1_INTERFACE
#define KYWC_OUTPUT_V1_INTERFACE
/**
 * @page page_iface_kywc_output_v1 kywc_output_v1
 * @section page_iface_kywc_output_v1_desc Description
 *
 * A output has some read-only properties: modes, name, description, 
 * physical_size. These cannot be changed by clients.
 *
 * Properties sent via this interface are applied atomically via the
 * kywc_output_manager.done event. No guarantees are made regarding the order
 * in which properties are sent.
 * @section page_iface_kywc_output_v1_api API
 * See @ref iface_kywc_output_v1.
 */
/**
 * @defgroup iface_kywc_output_v1 The kywc_output_v1 interface
 *
 * A output has some read-only properties: modes, name, description, 
 * physical_size. These cannot be changed by clients.
 *
 * Properties sent via this interface are applied atomically via the
 * kywc_output_manager.done event. No guarantees are made regarding the order
 * in which properties are sent.
 */
extern const struct wl_interface kywc_output_v1_interface;
#endif
#ifndef KYWC_OUTPUT_MODE_V1_INTERFACE
#define KYWC_OUTPUT_MODE_V1_INTERFACE
/**
 * @page page_iface_kywc_output_mode_v1 kywc_output_mode_v1
 * @section page_iface_kywc_output_mode_v1_desc Description
 *
 * This object describes an output mode.
 *
 * Properties sent via this interface are applied atomically via the
 * kywc_output_manager.done event. No guarantees are made regarding the order
 * in which properties are sent.
 * @section page_iface_kywc_output_mode_v1_api API
 * See @ref iface_kywc_output_mode_v1.
 */
/**
 * @defgroup iface_kywc_output_mode_v1 The kywc_output_mode_v1 interface
 *
 * This object describes an output mode.
 *
 * Properties sent via this interface are applied atomically via the
 * kywc_output_manager.done event. No guarantees are made regarding the order
 * in which properties are sent.
 */
extern const struct wl_interface kywc_output_mode_v1_interface;
#endif

/**
 * @ingroup iface_kywc_output_manager_v1
 * @struct kywc_output_manager_v1_listener
 */
struct kywc_output_manager_v1_listener {
	/**
	 * introduce a new output
	 *
	 * This event introduces a new output. This happens whenever a
	 * new output appears (e.g. a monitor is plugged in) or after the
	 * output manager is bound.
	 * @param uuid Unique id of the output
	 */
	void (*output)(void *data,
		       struct kywc_output_manager_v1 *kywc_output_manager_v1,
		       struct kywc_output_v1 *output,
		       const char *uuid);
	/**
	 * current primary output
	 *
	 * This events is sent when the output will become the primary
	 * output.
	 */
	void (*primary)(void *data,
			struct kywc_output_manager_v1 *kywc_output_manager_v1,
			struct kywc_output_v1 *output);
	/**
	 * sent all information about current configuration
	 *
	 * This event is sent after all information has been sent after
	 * binding to the output manager object and after any subsequent
	 * changes. This applies to child output and mode objects as well.
	 *
	 * This allows changes to the output configuration to be seen as
	 * atomic, even if they happen via multiple events.
	 */
	void (*done)(void *data,
		     struct kywc_output_manager_v1 *kywc_output_manager_v1);
	/**
	 * the compositor has finished with the manager
	 *
	 * This event indicates that the compositor is done sending
	 * manager events. The compositor will destroy the object
	 * immediately after sending this event, so it will become invalid
	 * and the client should release any resources associated with it.
	 */
	void (*finished)(void *data,
			 struct kywc_output_manager_v1 *kywc_output_manager_v1);
};

/**
 * @ingroup iface_kywc_output_manager_v1
 */
static inline int
kywc_output_manager_v1_add_listener(struct kywc_output_manager_v1 *kywc_output_manager_v1,
				    const struct kywc_output_manager_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) kywc_output_manager_v1,
				     (void (**)(void)) listener, data);
}

#define KYWC_OUTPUT_MANAGER_V1_STOP 0

/**
 * @ingroup iface_kywc_output_manager_v1
 */
#define KYWC_OUTPUT_MANAGER_V1_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_manager_v1
 */
#define KYWC_OUTPUT_MANAGER_V1_PRIMARY_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_manager_v1
 */
#define KYWC_OUTPUT_MANAGER_V1_DONE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_manager_v1
 */
#define KYWC_OUTPUT_MANAGER_V1_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_kywc_output_manager_v1
 */
#define KYWC_OUTPUT_MANAGER_V1_STOP_SINCE_VERSION 1

/** @ingroup iface_kywc_output_manager_v1 */
static inline void
kywc_output_manager_v1_set_user_data(struct kywc_output_manager_v1 *kywc_output_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) kywc_output_manager_v1, user_data);
}

/** @ingroup iface_kywc_output_manager_v1 */
static inline void *
kywc_output_manager_v1_get_user_data(struct kywc_output_manager_v1 *kywc_output_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) kywc_output_manager_v1);
}

static inline uint32_t
kywc_output_manager_v1_get_version(struct kywc_output_manager_v1 *kywc_output_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) kywc_output_manager_v1);
}

/** @ingroup iface_kywc_output_manager_v1 */
static inline void
kywc_output_manager_v1_destroy(struct kywc_output_manager_v1 *kywc_output_manager_v1)
{
	wl_proxy_destroy((struct wl_proxy *) kywc_output_manager_v1);
}

/**
 * @ingroup iface_kywc_output_manager_v1
 *
 * Indicates the client no longer wishes to receive events for output
 * configuration changes. However the compositor may emit further events,
 * until the finished event is emitted.
 *
 * The client must not send any more requests after this one.
 */
static inline void
kywc_output_manager_v1_stop(struct kywc_output_manager_v1 *kywc_output_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_output_manager_v1,
			 KYWC_OUTPUT_MANAGER_V1_STOP, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_output_manager_v1), 0);
}

#ifndef KYWC_OUTPUT_V1_CAPABILITY_ENUM
#define KYWC_OUTPUT_V1_CAPABILITY_ENUM
/**
 * @ingroup iface_kywc_output_v1
 * describes capabilities of the outputdevice
 *
 * Describes what capabilities this device has.
 */
enum kywc_output_v1_capability {
	/**
	 * if this output can support power(dpms)
	 */
	KYWC_OUTPUT_V1_CAPABILITY_POWER = 1,
	/**
	 * if this output supports brightness
	 */
	KYWC_OUTPUT_V1_CAPABILITY_BRIGHTNESS = 2,
	/**
	 * if setting the color temperature is possible
	 */
	KYWC_OUTPUT_V1_CAPABILITY_COLOR_TEMP = 4,
};
#endif /* KYWC_OUTPUT_V1_CAPABILITY_ENUM */

/**
 * @ingroup iface_kywc_output_v1
 * @struct kywc_output_v1_listener
 */
struct kywc_output_v1_listener {
	/**
	 * output name
	 *
	 * This event describes the output name.
	 *
	 * The name event is sent after a kywc_output object is created.
	 * This event is only sent once per object, and the name does not
	 * change over the lifetime of the kywc_output object.
	 */
	void (*name)(void *data,
		     struct kywc_output_v1 *kywc_output_v1,
		     const char *name);
	/**
	 * output monitor manufacturer
	 *
	 * This event describes the manufacturer of the output monitor.
	 */
	void (*make)(void *data,
		     struct kywc_output_v1 *kywc_output_v1,
		     const char *make);
	/**
	 * output monitor model
	 *
	 * This event describes the model of the output monitor.
	 */
	void (*model)(void *data,
		      struct kywc_output_v1 *kywc_output_v1,
		      const char *model);
	/**
	 * output serial number
	 *
	 * This event describes the serial number of the output monitor.
	 */
	void (*serial_number)(void *data,
			      struct kywc_output_v1 *kywc_output_v1,
			      const char *serial_number);
	/**
	 * output description
	 *
	 * This event describes a human-readable description of the
	 * output.
	 */
	void (*description)(void *data,
			    struct kywc_output_v1 *kywc_output_v1,
			    const char *description);
	/**
	 * output monitor physical size
	 *
	 * This event describes the physical size of the monitor. This
	 * event is only sent if has a physical size (e.g. is not a
	 * projector or a virtual device).
	 * @param width width in millimeters of the output
	 * @param height height in millimeters of the output
	 */
	void (*physical_size)(void *data,
			      struct kywc_output_v1 *kywc_output_v1,
			      int32_t width,
			      int32_t height);
	/**
	 * introduce a mode
	 *
	 * This event introduces a mode for this monitor. It is sent once
	 * per supported mode.
	 */
	void (*mode)(void *data,
		     struct kywc_output_v1 *kywc_output_v1,
		     struct kywc_output_mode_v1 *mode);
	/**
	 * capability flags
	 *
	 * What capabilities this output has, sent on startup before the
	 * first done event.
	 */
	void (*capabilities)(void *data,
			     struct kywc_output_v1 *kywc_output_v1,
			     uint32_t flags);
	/**
	 * the output is enabled or disabled
	 *
	 * This event describes whether the output is enabled. A disabled
	 * output is not mapped to a region of the global compositor space.
	 *
	 * When a output is disabled, some properties (current_mode,
	 * position, transform and scale) are irrelevant.
	 * @param enabled zero if disabled, non-zero if enabled
	 */
	void (*enabled)(void *data,
			struct kywc_output_v1 *kywc_output_v1,
			int32_t enabled);
	/**
	 * current mode
	 *
	 * This event describes the mode currently in use for this
	 * output. It is only sent if the output is enabled.
	 */
	void (*current_mode)(void *data,
			     struct kywc_output_v1 *kywc_output_v1,
			     struct kywc_output_mode_v1 *mode);
	/**
	 * current position
	 *
	 * This events describes the position of the output in the global
	 * compositor space. It is only sent if the output is enabled.
	 * @param x x position within the global compositor space
	 * @param y y position within the global compositor space
	 */
	void (*position)(void *data,
			 struct kywc_output_v1 *kywc_output_v1,
			 int32_t x,
			 int32_t y);
	/**
	 * current transformation
	 *
	 * This event describes the transformation currently applied to
	 * the output. It is only sent if the output is enabled.
	 */
	void (*transform)(void *data,
			  struct kywc_output_v1 *kywc_output_v1,
			  int32_t transform);
	/**
	 * current scale
	 *
	 * This events describes the scale of the output in the global
	 * compositor space. It is only sent if the output is enabled.
	 */
	void (*scale)(void *data,
		      struct kywc_output_v1 *kywc_output_v1,
		      wl_fixed_t scale);
	/**
	 * current power state
	 *
	 * This events describes the power(dpms) state.
	 */
	void (*power)(void *data,
		      struct kywc_output_v1 *kywc_output_v1,
		      uint32_t power);
	/**
	 * current output brightness
	 *
	 * This events describes the output brightness.
	 */
	void (*brightness)(void *data,
			   struct kywc_output_v1 *kywc_output_v1,
			   uint32_t brightness);
	/**
	 * current color temperature
	 *
	 * This events describes the output color temperature.
	 */
	void (*color_temp)(void *data,
			   struct kywc_output_v1 *kywc_output_v1,
			   uint32_t color_temp);
	/**
	 * the output has disappeared
	 *
	 * This event indicates that the output is no longer available.
	 * The output object becomes inert. Clients should send a destroy
	 * request and release any resources associated with it.
	 */
	void (*finished)(void *data,
			 struct kywc_output_v1 *kywc_output_v1);
};

/**
 * @ingroup iface_kywc_output_v1
 */
static inline int
kywc_output_v1_add_listener(struct kywc_output_v1 *kywc_output_v1,
			    const struct kywc_output_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) kywc_output_v1,
				     (void (**)(void)) listener, data);
}

#define KYWC_OUTPUT_V1_DESTROY 0

/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_NAME_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_MAKE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_MODEL_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_SERIAL_NUMBER_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_DESCRIPTION_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_PHYSICAL_SIZE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_MODE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_CAPABILITIES_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_ENABLED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_CURRENT_MODE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_POSITION_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_TRANSFORM_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_SCALE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_POWER_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_BRIGHTNESS_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_COLOR_TEMP_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_kywc_output_v1
 */
#define KYWC_OUTPUT_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_kywc_output_v1 */
static inline void
kywc_output_v1_set_user_data(struct kywc_output_v1 *kywc_output_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) kywc_output_v1, user_data);
}

/** @ingroup iface_kywc_output_v1 */
static inline void *
kywc_output_v1_get_user_data(struct kywc_output_v1 *kywc_output_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) kywc_output_v1);
}

static inline uint32_t
kywc_output_v1_get_version(struct kywc_output_v1 *kywc_output_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) kywc_output_v1);
}

/**
 * @ingroup iface_kywc_output_v1
 *
 * This request indicates that the client will no longer use this output object.
 */
static inline void
kywc_output_v1_destroy(struct kywc_output_v1 *kywc_output_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_output_v1,
			 KYWC_OUTPUT_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_output_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_kywc_output_mode_v1
 * @struct kywc_output_mode_v1_listener
 */
struct kywc_output_mode_v1_listener {
	/**
	 * mode size
	 *
	 * This event describes the mode size. The size is given in
	 * physical hardware units of the output device. This is not
	 * necessarily the same as the output size in the global compositor
	 * space. For instance, the output may be scaled or transformed.
	 * @param width width of the mode in hardware units
	 * @param height height of the mode in hardware units
	 */
	void (*size)(void *data,
		     struct kywc_output_mode_v1 *kywc_output_mode_v1,
		     int32_t width,
		     int32_t height);
	/**
	 * mode refresh rate
	 *
	 * This event describes the mode's fixed vertical refresh rate.
	 * It is only sent if the mode has a fixed refresh rate.
	 * @param refresh vertical refresh rate in mHz
	 */
	void (*refresh)(void *data,
			struct kywc_output_mode_v1 *kywc_output_mode_v1,
			int32_t refresh);
	/**
	 * mode is preferred
	 *
	 * This event advertises this mode as preferred.
	 */
	void (*preferred)(void *data,
			  struct kywc_output_mode_v1 *kywc_output_mode_v1);
	/**
	 * the mode has disappeared
	 *
	 * This event indicates that the mode is no longer available. The
	 * mode object becomes inert. Clients should send a destroy request
	 * and release any resources associated with it.
	 */
	void (*finished)(void *data,
			 struct kywc_output_mode_v1 *kywc_output_mode_v1);
};

/**
 * @ingroup iface_kywc_output_mode_v1
 */
static inline int
kywc_output_mode_v1_add_listener(struct kywc_output_mode_v1 *kywc_output_mode_v1,
				 const struct kywc_output_mode_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) kywc_output_mode_v1,
				     (void (**)(void)) listener, data);
}

#define KYWC_OUTPUT_MODE_V1_DESTROY 0

/**
 * @ingroup iface_kywc_output_mode_v1
 */
#define KYWC_OUTPUT_MODE_V1_SIZE_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_mode_v1
 */
#define KYWC_OUTPUT_MODE_V1_REFRESH_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_mode_v1
 */
#define KYWC_OUTPUT_MODE_V1_PREFERRED_SINCE_VERSION 1
/**
 * @ingroup iface_kywc_output_mode_v1
 */
#define KYWC_OUTPUT_MODE_V1_FINISHED_SINCE_VERSION 1

/**
 * @ingroup iface_kywc_output_mode_v1
 */
#define KYWC_OUTPUT_MODE_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_kywc_output_mode_v1 */
static inline void
kywc_output_mode_v1_set_user_data(struct kywc_output_mode_v1 *kywc_output_mode_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) kywc_output_mode_v1, user_data);
}

/** @ingroup iface_kywc_output_mode_v1 */
static inline void *
kywc_output_mode_v1_get_user_data(struct kywc_output_mode_v1 *kywc_output_mode_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) kywc_output_mode_v1);
}

static inline uint32_t
kywc_output_mode_v1_get_version(struct kywc_output_mode_v1 *kywc_output_mode_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) kywc_output_mode_v1);
}

/**
 * @ingroup iface_kywc_output_mode_v1
 *
 * This request indicates that the client will no longer use this mode
 * object.
 */
static inline void
kywc_output_mode_v1_destroy(struct kywc_output_mode_v1 *kywc_output_mode_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) kywc_output_mode_v1,
			 KYWC_OUTPUT_MODE_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) kywc_output_mode_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifdef  __cplusplus
}
#endif

#endif
