/* Generated by wayland-scanner 1.23.1 */

/*
 * SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
 * SPDX-License-Identifier: MulanPSL-2.0
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface kywc_output_mode_v1_interface;
extern const struct wl_interface kywc_output_v1_interface;

static const struct wl_interface *kywc_output_v1_types[] = {
	NULL,
	NULL,
	&kywc_output_v1_interface,
	NULL,
	&kywc_output_v1_interface,
	&kywc_output_mode_v1_interface,
	&kywc_output_mode_v1_interface,
};

static const struct wl_message kywc_output_manager_v1_requests[] = {
	{ "stop", "", kywc_output_v1_types + 0 },
};

static const struct wl_message kywc_output_manager_v1_events[] = {
	{ "output", "ns", kywc_output_v1_types + 2 },
	{ "primary", "o", kywc_output_v1_types + 4 },
	{ "done", "", kywc_output_v1_types + 0 },
	{ "finished", "", kywc_output_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_output_manager_v1_interface = {
	"kywc_output_manager_v1", 1,
	1, kywc_output_manager_v1_requests,
	4, kywc_output_manager_v1_events,
};

static const struct wl_message kywc_output_v1_requests[] = {
	{ "destroy", "", kywc_output_v1_types + 0 },
};

static const struct wl_message kywc_output_v1_events[] = {
	{ "name", "s", kywc_output_v1_types + 0 },
	{ "make", "s", kywc_output_v1_types + 0 },
	{ "model", "s", kywc_output_v1_types + 0 },
	{ "serial_number", "s", kywc_output_v1_types + 0 },
	{ "description", "s", kywc_output_v1_types + 0 },
	{ "physical_size", "ii", kywc_output_v1_types + 0 },
	{ "mode", "n", kywc_output_v1_types + 5 },
	{ "capabilities", "u", kywc_output_v1_types + 0 },
	{ "enabled", "i", kywc_output_v1_types + 0 },
	{ "current_mode", "o", kywc_output_v1_types + 6 },
	{ "position", "ii", kywc_output_v1_types + 0 },
	{ "transform", "i", kywc_output_v1_types + 0 },
	{ "scale", "f", kywc_output_v1_types + 0 },
	{ "power", "u", kywc_output_v1_types + 0 },
	{ "brightness", "u", kywc_output_v1_types + 0 },
	{ "color_temp", "u", kywc_output_v1_types + 0 },
	{ "finished", "", kywc_output_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_output_v1_interface = {
	"kywc_output_v1", 1,
	1, kywc_output_v1_requests,
	17, kywc_output_v1_events,
};

static const struct wl_message kywc_output_mode_v1_requests[] = {
	{ "destroy", "", kywc_output_v1_types + 0 },
};

static const struct wl_message kywc_output_mode_v1_events[] = {
	{ "size", "ii", kywc_output_v1_types + 0 },
	{ "refresh", "i", kywc_output_v1_types + 0 },
	{ "preferred", "", kywc_output_v1_types + 0 },
	{ "finished", "", kywc_output_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_output_mode_v1_interface = {
	"kywc_output_mode_v1", 1,
	1, kywc_output_mode_v1_requests,
	4, kywc_output_mode_v1_events,
};

