/* Generated by wayland-scanner 1.23.1 */

/*
 * SPDX-FileCopyrightText: 2024 KylinSoft Co., Ltd.
 * SPDX-License-Identifier: MulanPSL-2.0
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface kywc_capture_cursor_v1_interface;
extern const struct wl_interface kywc_capture_frame_v1_interface;
extern const struct wl_interface wl_seat_interface;

static const struct wl_interface *kywc_capture_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	&kywc_capture_frame_v1_interface,
	NULL,
	NULL,
	&kywc_capture_frame_v1_interface,
	NULL,
	NULL,
	&kywc_capture_frame_v1_interface,
	NULL,
	NULL,
	&kywc_capture_cursor_v1_interface,
	&wl_seat_interface,
	&kywc_capture_frame_v1_interface,
};

static const struct wl_message kywc_capture_manager_v1_requests[] = {
	{ "capture_output", "nis", kywc_capture_v1_types + 9 },
	{ "capture_workspace", "nss", kywc_capture_v1_types + 12 },
	{ "capture_toplevel", "nsu", kywc_capture_v1_types + 15 },
	{ "capture_cursor", "no?o", kywc_capture_v1_types + 18 },
	{ "destroy", "", kywc_capture_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_capture_manager_v1_interface = {
	"kywc_capture_manager_v1", 2,
	5, kywc_capture_manager_v1_requests,
	0, NULL,
};

static const struct wl_message kywc_capture_frame_v1_requests[] = {
	{ "destroy", "", kywc_capture_v1_types + 0 },
	{ "release_buffer", "u", kywc_capture_v1_types + 0 },
};

static const struct wl_message kywc_capture_frame_v1_events[] = {
	{ "failed", "", kywc_capture_v1_types + 0 },
	{ "cancelled", "", kywc_capture_v1_types + 0 },
	{ "buffer", "huuuuuuuu", kywc_capture_v1_types + 0 },
	{ "buffer_with_plane", "2uhuu", kywc_capture_v1_types + 0 },
	{ "buffer_done", "2", kywc_capture_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_capture_frame_v1_interface = {
	"kywc_capture_frame_v1", 2,
	2, kywc_capture_frame_v1_requests,
	5, kywc_capture_frame_v1_events,
};

static const struct wl_message kywc_capture_cursor_v1_requests[] = {
	{ "destroy", "", kywc_capture_v1_types + 0 },
};

static const struct wl_message kywc_capture_cursor_v1_events[] = {
	{ "enter", "", kywc_capture_v1_types + 0 },
	{ "leave", "", kywc_capture_v1_types + 0 },
	{ "position", "ii", kywc_capture_v1_types + 0 },
	{ "hotspot", "ii", kywc_capture_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface kywc_capture_cursor_v1_interface = {
	"kywc_capture_cursor_v1", 2,
	1, kywc_capture_cursor_v1_requests,
	4, kywc_capture_cursor_v1_events,
};

